import 'package:flutter/material.dart';
import '../services/api_service.dart';

class HomeScreen extends StatefulWidget { const HomeScreen({super.key}); @override State<HomeScreen> createState()=>_HomeScreenState(); }
class _HomeScreenState extends State<HomeScreen> {
 final url=TextEditingController(); String quality='720p', format='MP4', status='Ready'; Map<String,dynamic>? info;
 final qs=['360p','480p','720p','1080p','1440p','2160p']; final fs=['MP4','WebM','MKV','MP3','M4A'];
 Future<ApiService> api() async => ApiService(token: await _token()); Future<String?> _token() async { /* token can be wired from AuthService */ return null; }
 void msg(String s)=>setState(()=>status=s);
 Future<void> analyze() async { if(url.text.trim().isEmpty){msg('Enter a URL.');return;} try{ final a=await api(); info=await a.post('/analyze',{'url':url.text.trim(),'quality':quality,'format':format}); msg('Analysis complete.'); setState((){}); }catch(e){msg(e.toString());} }
 Future<void> download() async { try{ final a=await api(); final r=await a.post('/download',{'url':url.text.trim(),'quality':quality,'format':format}); msg('Download ready: ${r['file_name']}'); }catch(e){msg(e.toString());} }
 @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('⬇ NexDownloader'),actions:[Padding(padding:const EdgeInsets.all(8),child:FilledButton(onPressed:(){},child:const Text('Premium $5')))]),body:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(24),child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:700),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const SizedBox(height:20),const Text('Download your media.',textAlign:TextAlign.center,style:TextStyle(fontSize:34,fontWeight:FontWeight.bold)),const SizedBox(height:24),TextField(controller:url,decoration:const InputDecoration(labelText:'Paste supported URL',border:OutlineInputBorder())),const SizedBox(height:12),FilledButton.icon(onPressed:analyze,icon:const Icon(Icons.search),label:const Text('Analyze')),const SizedBox(height:18),DropdownButtonFormField(value:quality,decoration:const InputDecoration(labelText:'Quality',border:OutlineInputBorder()),items:qs.map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(x)=>setState(()=>quality=x!)),const SizedBox(height:12),DropdownButtonFormField(value:format,decoration:const InputDecoration(labelText:'Format',border:OutlineInputBorder()),items:fs.map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(x)=>setState(()=>format=x!)),const SizedBox(height:18),FilledButton.icon(onPressed:download,icon:const Icon(Icons.download),label:const Text('Download')),const SizedBox(height:18),Card(child:Padding(padding:const EdgeInsets.all(16),child:Text(status))),if(info!=null) Padding(padding:const EdgeInsets.only(top:12),child:Text('Title: ${info!['title'] ?? 'Unknown'}')),const SizedBox(height:20),const Text('Free: up to 720p. Premium: higher quality where available.\nOnly download content you own or are authorized to download. DRM/access-control bypass is not supported.',textAlign:TextAlign.center)]))));
}
